spring:
  cloud:
    stream:
      function:
        definition: myConsumer
      bindings:
        myConsumer-in-0:
          destination: kinesis-lock-bug
          contentType: application/octet-stream
          binder: kinesis
          group: "kinesis-lock-bug"
